-- Generated by scripts/probes/_bt_population.py -- DO NOT HAND-EDIT the constants
-- below; they are read from ep_detector.py / constants.py at run time.
-- MIN_GAP_PCT=9.0 MIN_PREV_CLOSE=5.0
-- MIN_PREV_DAY_VOLUME=50000.0 MAX_TICKER_LEN=5
-- open-superset floor = MIN_GAP_PCT - 2.0pp = 7.0
WITH dc_all AS (
  -- LAG computed over the FULL table (not window-filtered) so the first window date's
  -- prev_close is the true prior session, not falsely NULL at the window boundary.
  SELECT trade_date, ticker, open_price, close, volume,
         LAG(close) OVER (PARTITION BY ticker ORDER BY trade_date) AS prev_close,
         LAG(volume) OVER (PARTITION BY ticker ORDER BY trade_date) AS prev_volume,
         LAG(trade_date) OVER (PARTITION BY ticker ORDER BY trade_date) AS prev_trade_date
  FROM mi_daily_closes
),
dc AS (
  SELECT * FROM dc_all
  WHERE trade_date BETWEEN '2026-04-13' AND (SELECT max(trade_date) FROM mi_daily_closes)
),
open_seed AS (
  SELECT trade_date, ticker
  FROM dc
  WHERE prev_close IS NOT NULL AND prev_close > 0 AND open_price IS NOT NULL
    AND (open_price - prev_close) / prev_close * 100.0 >= 7.0
),
scanlog_seed AS (
  SELECT scan_date AS trade_date, ticker, max(gap_pct) AS scanlog_max_gap
  FROM mi_ep_scan_log
  WHERE scan_date BETWEEN '2026-04-13' AND (SELECT max(trade_date) FROM mi_daily_closes)
  GROUP BY scan_date, ticker
  HAVING max(gap_pct) >= 9.0
),
seed_union AS (
  SELECT trade_date, ticker FROM open_seed
  UNION
  SELECT trade_date, ticker FROM scanlog_seed
),
bar_days AS (
  SELECT ticker, (bar_time AT TIME ZONE 'America/New_York')::date AS d,
         bool_or(EXTRACT(HOUR FROM bar_time AT TIME ZONE 'America/New_York') = 9
                  AND EXTRACT(MINUTE FROM bar_time AT TIME ZONE 'America/New_York') = 30) AS has_orb_bar
  FROM mi_intraday_bars
  GROUP BY ticker, d
)
SELECT
  su.trade_date,
  su.ticker,
  round(dc.open_price::numeric, 3),
  round(dc.prev_close::numeric, 3),
  dc.prev_volume,
  round(((dc.open_price - dc.prev_close) / NULLIF(dc.prev_close, 0) * 100.0)::numeric, 3),
  round(sl.scanlog_max_gap::numeric, 3),
  (os.trade_date IS NOT NULL),
  (sl.trade_date IS NOT NULL),
  COALESCE(bd.has_orb_bar, false),
  (bd.d IS NOT NULL),
  dc.prev_trade_date,
  (dc.trade_date - dc.prev_trade_date)
FROM seed_union su
JOIN dc ON dc.trade_date = su.trade_date AND dc.ticker = su.ticker
LEFT JOIN open_seed os ON os.trade_date = su.trade_date AND os.ticker = su.ticker
LEFT JOIN scanlog_seed sl ON sl.trade_date = su.trade_date AND sl.ticker = su.ticker
LEFT JOIN bar_days bd ON bd.ticker = su.ticker AND bd.d = su.trade_date
WHERE dc.prev_close >= 5.0
  AND dc.prev_volume >= 50000.0
  AND length(su.ticker) <= 5
  AND su.ticker NOT IN ('AGQ','BNKU','BNO','BOIL','BRZU','BZQ','CONL','CORN','CPER','CRCA','CWEB','DBA','DBC','DBO','DIA','DRIP','DRN','DRV','DULL','DUST','EDC','EDZ','ERX','ERY','FAS','FAZ','FNGD','FNGU','GDX','GDXD','GDXJ','GLD','GLL','GSG','GUSH','IAU','IBB','IVV','IWM','JDST','JNUG','KOLD','KRE','LABD','LABU','MSTU','MSTZ','MULL','MUU','NRGD','NRGU','NUGT','NVDL','NVDS','OKLS','PALL','PDBC','PPLT','QBTZ','QID','QLD','QQQ','RETL','RSP','SCO','SDOW','SDS','SLV','SMH','SNXX','SOXL','SOXS','SOYB','SPXL','SPXS','SPY','SQQQ','SSO','SVIX','SVXY','TECL','TECS','TNA','TQQQ','TSLL','TZA','UCO','UDOW','UGL','UNG','UPRO','USO','UVIX','UVXY','VOO','VTI','VXX','WDCX','WEAT','XBI','XLB','XLC','XLE','XLF','XLI','XLK','XLP','XLRE','XLU','XLV','XLY','YANG','YINN','ZSL')
ORDER BY su.trade_date, su.ticker;
