"""#687 INDEPENDENT CHECK — builds check_pull.sql (ONE read-only prod round-trip, captured once to check_pull_out.txt).
Own derivation of the gap-up list: raw (split-UNadjusted) floors applied IN SQL from the captured Polygon split table
(splits executed on/before the 2026-09-29 pull only), prior-row vs prior-session date carried, ADV / extension / ATR14
recomputed per candidate; a split-adjustment integrity check; ticker first/last-row histograms (survivorship)."""
import json, re
from pathlib import Path
HERE = Path(__file__).resolve().parent
s = [x for x in json.load(open(HERE / "splits.json")) if re.fullmatch(r"[A-Z]{1,5}", x["ticker"])]
vals_all = ",\n".join(f"('{x['ticker']}','{x['execution_date']}'::date,{float(x['split_from'])},{float(x['split_to'])})" for x in s)
unk = "ZVZZT CCCXW USARW CIFRW CETH LUNRW FJIKY FNGB HONDW KWHIY NEXI HCP YMAB CZOO KTRA SWTX RYI SHYF FNGA QSG ZJZZT PXIU ETQ BTCM POL SAVAW EXAI DWACW CPSI BGNE SWIN MPLN HBI AVTE BYON AZPN CEIX AXL PX CRGX".split()
sql = f"""-- #687 INDEPENDENT CHECK read-only prod pull (captured once). Generated by check_make_sql.py.
\\set ON_ERROR_STOP 1
BEGIN TRANSACTION READ ONLY;
\\echo === DATES ===
SELECT trade_date, count(*) AS n FROM mi_daily_closes WHERE trade_date BETWEEN '2023-09-01' AND '2026-09-29' GROUP BY 1 ORDER BY 1;
\\echo === SPLITCHECK ===
WITH s(ticker, xd, sfrom, sto) AS (VALUES
{vals_all})
SELECT s.ticker, s.xd, s.sfrom, s.sto, p.trade_date AS pdate, p.close AS pclose, x.trade_date AS xdate, x.open_price AS xopen, x.close AS xclose
FROM s
LEFT JOIN LATERAL (SELECT trade_date, close FROM mi_daily_closes d WHERE d.ticker = s.ticker AND d.trade_date < s.xd AND d.trade_date >= s.xd - 10 ORDER BY trade_date DESC LIMIT 1) p ON true
LEFT JOIN LATERAL (SELECT trade_date, open_price, close FROM mi_daily_closes d WHERE d.ticker = s.ticker AND d.trade_date >= s.xd AND d.trade_date <= s.xd + 10 ORDER BY trade_date LIMIT 1) x ON true
WHERE s.xd <= '2026-09-29';
\\echo === POP ===
WITH s(ticker, xd, sfrom, sto) AS (VALUES
{vals_all}),
sp AS (SELECT * FROM s WHERE xd <= '2026-09-29' AND sfrom > 0 AND sto > 0),
b AS (
  SELECT ticker, trade_date, open_price AS o, close AS c, volume AS v,
         lag(close) OVER w AS pc, lag(volume) OVER w AS pv, lag(trade_date) OVER w AS pdate,
         avg(volume) OVER (PARTITION BY ticker ORDER BY trade_date ROWS BETWEEN 20 PRECEDING AND 1 PRECEDING) AS avgv20,
         count(*) OVER (PARTITION BY ticker ORDER BY trade_date ROWS BETWEEN 20 PRECEDING AND 1 PRECEDING) AS n20
  FROM mi_daily_closes
  WHERE trade_date >= '2023-10-01' AND trade_date <= '2026-04-30' AND ticker ~ '^[A-Z]{{1,5}}$'
  WINDOW w AS (PARTITION BY ticker ORDER BY trade_date)
),
g AS (SELECT * FROM b WHERE trade_date >= '2024-01-02' AND o IS NOT NULL AND pc > 0 AND (o - pc) / pc >= 0.09),
f AS (
  SELECT g.ticker, g.trade_date, g.o, g.c, g.v, g.pc, g.pv, g.pdate, g.avgv20, g.n20,
         COALESCE(exp(sum(ln(sp.sto / sp.sfrom))), 1.0) AS fac
  FROM g LEFT JOIN sp ON sp.ticker = g.ticker AND sp.xd > g.trade_date
  GROUP BY g.ticker, g.trade_date, g.o, g.c, g.v, g.pc, g.pv, g.pdate, g.avgv20, g.n20
),
k AS (SELECT * FROM f WHERE pc * fac >= 5 AND pv / fac >= 50000)
SELECT k.ticker, k.trade_date, k.o, k.c, k.v, k.pc, k.pv, k.pdate, k.avgv20, k.n20, k.fac,
       ex.low_close, ad.adv_dollar, ad.nadv, at.atr14, at.atr_lastc, at.atr_n
FROM k
LEFT JOIN LATERAL (SELECT min(close) AS low_close FROM mi_daily_closes d
                   WHERE d.ticker = k.ticker AND d.trade_date >= k.trade_date - 10 AND d.trade_date < k.trade_date) ex ON true
LEFT JOIN LATERAL (SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY close * volume) AS adv_dollar, count(*) AS nadv
                   FROM mi_daily_closes d
                   WHERE d.ticker = k.ticker AND d.trade_date >= k.trade_date - 30 AND d.trade_date < k.trade_date AND d.volume > 0) ad ON true
LEFT JOIN LATERAL (
  WITH w AS (
    SELECT high_price AS h, low_price AS l, close AS c,
           lag(close) OVER (ORDER BY trade_date) AS pcl,
           row_number() OVER (ORDER BY trade_date DESC) AS rn,
           count(*) OVER () AS n
    FROM mi_daily_closes d
    WHERE d.ticker = k.ticker AND d.trade_date >= k.trade_date - 35 AND d.trade_date < k.trade_date
      AND d.high_price IS NOT NULL AND d.low_price IS NOT NULL AND d.close IS NOT NULL)
  SELECT avg(greatest(h - l, abs(h - pcl), abs(l - pcl))) FILTER (WHERE pcl IS NOT NULL AND rn <= 14) AS atr14,
         max(c) FILTER (WHERE rn = 1) AS atr_lastc, max(n) AS atr_n
  FROM w) at ON true
ORDER BY k.trade_date, k.ticker;
\\echo === SURV_LAST ===
SELECT date_trunc('month', lastd)::date AS m, count(*) AS tickers FROM (
  SELECT ticker, max(trade_date) AS lastd FROM mi_daily_closes WHERE ticker ~ '^[A-Z]{{1,5}}$' GROUP BY ticker) x GROUP BY 1 ORDER BY 1;
\\echo === SURV_FIRST ===
SELECT date_trunc('month', firstd)::date AS m, count(*) AS tickers FROM (
  SELECT ticker, min(trade_date) AS firstd FROM mi_daily_closes WHERE ticker ~ '^[A-Z]{{1,5}}$' GROUP BY ticker) x GROUP BY 1 ORDER BY 1;
\\echo === UNK_SPAN ===
SELECT ticker, min(trade_date) AS firstd, max(trade_date) AS lastd, count(*) AS n FROM mi_daily_closes
WHERE ticker IN ({",".join(f"'{t}'" for t in unk)}) GROUP BY ticker ORDER BY ticker;
ROLLBACK;
"""
open(HERE / "check_pull.sql", "w").write(sql)
print("wrote check_pull.sql", len(sql), "bytes;", len(s), "splits")
