-- READ-ONLY (SELECT only). Generated by run_probe.py gen. Run once; read q3_verify.out.
SELECT 'rows' AS tag, r.ticker, r.alert_date::text, r.engine_theme::text, r.judge_theme::text,
       coalesce(r.theme_name_7d, '') AS theme_name_7d, coalesce(r.theme_stage_7d, '') AS theme_stage_7d
  FROM (
WITH alerts AS (
                SELECT DISTINCT ON (ticker, alert_date)
                       ticker, alert_date, in_active_theme, fire_axes
                  FROM mi_ep_alerts
                 WHERE alert_date BETWEEN '2026-09-12'::date AND '2026-10-11'::date
                   AND fire_axes IS NOT NULL
                 ORDER BY ticker, alert_date, id DESC
            )
            SELECT a.ticker, a.alert_date,
                   (a.in_active_theme IS TRUE)                 AS engine_theme,
                   COALESCE('theme' = ANY(a.fire_axes), FALSE) AS judge_theme,
                   s.theme_name_7d, s.theme_stage_7d
              FROM alerts a
              JOIN mi_theme_axis_shadow s
                ON s.ticker = a.ticker AND s.alert_date = a.alert_date
             WHERE s.bounded_matches_unbounded IS TRUE
             ORDER BY a.alert_date DESC, a.ticker
) r;

SELECT 'direct_week' AS tag,
       count(*)::text AS n,
       count(*) FILTER (WHERE x.engine)::text AS engine_themed,
       count(*) FILTER (WHERE x.judge)::text AS judge_themed
  FROM (
    SELECT a.ticker, a.alert_date,
           bool_or(a.in_active_theme IS TRUE) AS engine,
           bool_or(COALESCE('theme' = ANY(a.fire_axes), FALSE)) AS judge
      FROM mi_ep_alerts a
     WHERE a.alert_date BETWEEN '2026-10-04'::date AND '2026-10-11'::date
       AND a.fire_axes IS NOT NULL 
       AND EXISTS (SELECT 1 FROM mi_theme_axis_shadow s
                    WHERE s.ticker = a.ticker AND s.alert_date = a.alert_date
                      AND s.bounded_matches_unbounded IS TRUE )
     GROUP BY a.ticker, a.alert_date
  ) x;


SELECT 'direct_trail' AS tag,
       count(*)::text AS n,
       count(*) FILTER (WHERE x.engine)::text AS engine_themed,
       count(*) FILTER (WHERE x.judge)::text AS judge_themed
  FROM (
    SELECT a.ticker, a.alert_date,
           bool_or(a.in_active_theme IS TRUE) AS engine,
           bool_or(COALESCE('theme' = ANY(a.fire_axes), FALSE)) AS judge
      FROM mi_ep_alerts a
     WHERE a.alert_date BETWEEN '2026-09-12'::date AND '2026-10-11'::date
       AND a.fire_axes IS NOT NULL 
       AND EXISTS (SELECT 1 FROM mi_theme_axis_shadow s
                    WHERE s.ticker = a.ticker AND s.alert_date = a.alert_date
                      AND s.bounded_matches_unbounded IS TRUE )
     GROUP BY a.ticker, a.alert_date
  ) x;


SELECT 'direct_trail_live_scan_only' AS tag,
       count(*)::text AS n,
       count(*) FILTER (WHERE x.engine)::text AS engine_themed,
       count(*) FILTER (WHERE x.judge)::text AS judge_themed
  FROM (
    SELECT a.ticker, a.alert_date,
           bool_or(a.in_active_theme IS TRUE) AS engine,
           bool_or(COALESCE('theme' = ANY(a.fire_axes), FALSE)) AS judge
      FROM mi_ep_alerts a
     WHERE a.alert_date BETWEEN '2026-09-12'::date AND '2026-10-11'::date
       AND a.fire_axes IS NOT NULL 
       AND EXISTS (SELECT 1 FROM mi_theme_axis_shadow s
                    WHERE s.ticker = a.ticker AND s.alert_date = a.alert_date
                      AND s.bounded_matches_unbounded IS TRUE AND s.source = 'live_scan')
     GROUP BY a.ticker, a.alert_date
  ) x;

SELECT 'ctx_all_adjudicated_trail' AS tag, count(*)::text AS n FROM (
              SELECT DISTINCT ticker, alert_date FROM mi_ep_alerts
               WHERE alert_date BETWEEN '2026-09-12'::date AND '2026-10-11'::date AND fire_axes IS NOT NULL) y;
SELECT 'ctx_adjudicated_with_shadow_row_trail' AS tag, count(*)::text AS n FROM (
              SELECT DISTINCT a.ticker, a.alert_date FROM mi_ep_alerts a
                JOIN mi_theme_axis_shadow s ON s.ticker = a.ticker AND s.alert_date = a.alert_date
               WHERE a.alert_date BETWEEN '2026-09-12'::date AND '2026-10-11'::date AND a.fire_axes IS NOT NULL) y;
