"""#486 weekly section — prod verification driver (READ-ONLY; SELECT only on prod).

  python scripts/probes/_wk1010_486/run_probe.py gen      # writes q3_verify.sql (the SHIPPED row SQL
                                                          #   + independent count SQL, same windows)
  ssh apollo@87.99.134.162 "docker exec -i apollo-postgres psql -U apollo -d apollo -A -F $'\\t'" \\
      < scripts/probes/_wk1010_486/q3_verify.sql > scripts/probes/_wk1010_486/q3_verify.out
  python scripts/probes/_wk1010_486/run_probe.py render   # parses q3_verify.out, runs the REAL
                                                          #   aggregator + formatter, writes
                                                          #   sample_render.txt incl. the cross-check

The row SQL is not re-typed here: it is CAPTURED from `db.get_engine_vs_judge_theme_rows` through a
recording pool, so what runs on prod is byte-for-byte what ships. The count SQL is written
independently (EXISTS + DISTINCT instead of the CTE's DISTINCT ON) so a bug in the shipped
de-duplication cannot hide behind an identical copy of itself.
"""
import asyncio
import sys
from datetime import date, timedelta
from pathlib import Path
from unittest.mock import AsyncMock, patch

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
sys.path.insert(0, str(ROOT))

# The Sunday run is 2026-10-11 08:00 ET. Data is complete through Fri 10-09 (market shut since).
TODAY = date(2026, 10, 11)
WINDOW_START = TODAY - timedelta(days=7)                      # run_weekly_review's own window
TRAIL_START = TODAY - timedelta(days=29)                      # trailing 30 days, inclusive
FETCH_START = min(WINDOW_START, TRAIL_START)


def _capture_row_sql() -> str:
    import agents.market_intelligence.db as dbmod
    from tests.conftest import make_mock_pool
    pool, conn = make_mock_pool()
    conn.fetch = AsyncMock(return_value=[])

    async def go():
        with patch.object(dbmod, "get_pool", new=AsyncMock(return_value=pool)):
            await dbmod.get_engine_vs_judge_theme_rows(FETCH_START, TODAY)
    asyncio.run(go())
    sql = conn.fetch.await_args.args[0]
    assert conn.fetch.await_args.args[1:] == (FETCH_START, TODAY)
    return (sql.replace("$1::date", f"'{FETCH_START}'::date")
               .replace("$2::date", f"'{TODAY}'::date").strip().rstrip(";"))


def _count_sql(tag: str, d1: date, d2: date, extra_alert: str = "", extra_shadow: str = "") -> str:
    return f"""
SELECT '{tag}' AS tag,
       count(*)::text AS n,
       count(*) FILTER (WHERE x.engine)::text AS engine_themed,
       count(*) FILTER (WHERE x.judge)::text AS judge_themed
  FROM (
    SELECT a.ticker, a.alert_date,
           bool_or(a.in_active_theme IS TRUE) AS engine,
           bool_or(COALESCE('theme' = ANY(a.fire_axes), FALSE)) AS judge
      FROM mi_ep_alerts a
     WHERE a.alert_date BETWEEN '{d1}'::date AND '{d2}'::date
       AND a.fire_axes IS NOT NULL {extra_alert}
       AND EXISTS (SELECT 1 FROM mi_theme_axis_shadow s
                    WHERE s.ticker = a.ticker AND s.alert_date = a.alert_date
                      AND s.bounded_matches_unbounded IS TRUE {extra_shadow})
     GROUP BY a.ticker, a.alert_date
  ) x;
"""


def gen() -> None:
    row_sql = _capture_row_sql()
    parts = [
        "-- READ-ONLY (SELECT only). Generated by run_probe.py gen. Run once; read q3_verify.out.",
        "SELECT 'rows' AS tag, r.ticker, r.alert_date::text, r.engine_theme::text, r.judge_theme::text,",
        "       coalesce(r.theme_name_7d, '') AS theme_name_7d, coalesce(r.theme_stage_7d, '') AS theme_stage_7d",
        "  FROM (", row_sql, ") r;",
        _count_sql("direct_week", WINDOW_START, TODAY),
        _count_sql("direct_trail", TRAIL_START, TODAY),
        # does adding source='live_scan' change the population? (the join to alerts should already do it)
        _count_sql("direct_trail_live_scan_only", TRAIL_START, TODAY, extra_shadow="AND s.source = 'live_scan'"),
        # context: how much does the bounded filter exclude? (all adjudicated alerts in the trailing window)
        f"""SELECT 'ctx_all_adjudicated_trail' AS tag, count(*)::text AS n FROM (
              SELECT DISTINCT ticker, alert_date FROM mi_ep_alerts
               WHERE alert_date BETWEEN '{TRAIL_START}'::date AND '{TODAY}'::date AND fire_axes IS NOT NULL) y;""",
        f"""SELECT 'ctx_adjudicated_with_shadow_row_trail' AS tag, count(*)::text AS n FROM (
              SELECT DISTINCT a.ticker, a.alert_date FROM mi_ep_alerts a
                JOIN mi_theme_axis_shadow s ON s.ticker = a.ticker AND s.alert_date = a.alert_date
               WHERE a.alert_date BETWEEN '{TRAIL_START}'::date AND '{TODAY}'::date AND a.fire_axes IS NOT NULL) y;""",
    ]
    (HERE / "q3_verify.sql").write_text("\n".join(parts) + "\n")
    print("wrote", HERE / "q3_verify.sql")


def _parse() -> tuple[list[dict], dict[str, dict]]:
    rows, counts = [], {}
    heads: dict[str, list[str]] = {}
    for ln in (HERE / "q3_verify.out").read_text().splitlines():
        cells = ln.split("\t")
        if not cells or not cells[0]:
            continue
        tag = cells[0]
        if tag == "tag":                                      # a header row: remember its columns
            heads["last"] = cells
            continue
        if tag.startswith("(") or tag.startswith("ERROR"):
            if tag.startswith("ERROR"):
                raise SystemExit(f"prod error in q3_verify.out: {ln}")
            continue
        if tag == "rows":
            _, ticker, ad, eng, jdg, name, stage = cells
            rows.append({"ticker": ticker, "alert_date": date.fromisoformat(ad),
                         "engine_theme": eng == "true", "judge_theme": jdg == "true",
                         "theme_name_7d": name or None, "theme_stage_7d": stage or None})
        else:
            counts[tag] = dict(zip(heads["last"][1:], cells[1:]))
    return rows, counts


def render() -> None:
    import agents.market_intelligence.system_review as sr
    rows, counts = _parse()
    seen = {}

    async def fake_fetch(a, b):
        seen["args"] = (a, b)
        return rows
    sr.get_engine_vs_judge_theme_rows = fake_fetch           # the ONLY thing replaced: the DB driver
    text, phrase = asyncio.run(sr._theme_agreement_section(WINDOW_START, TODAY))

    def agg(lo):
        return sr._aggregate_theme_agreement([r for r in rows if r["alert_date"] >= lo])
    wk, tr = agg(WINDOW_START), agg(TRAIL_START)
    checks = []
    for name, a, key in (("week", wk, "direct_week"), ("trail30", tr, "direct_trail")):
        d = counts[key]
        engine_agg, judge_agg = a["both"] + a["engine_only"], a["both"] + a["judge_only"]
        ok = (a["n"], engine_agg, judge_agg) == (int(d["n"]), int(d["engine_themed"]), int(d["judge_themed"]))
        checks.append((name, a["n"], engine_agg, judge_agg, d["n"], d["engine_themed"], d["judge_themed"], ok))
    ls = counts["direct_trail_live_scan_only"]
    out = [
        f"#486 sample render — as the Sun 2026-10-11 08:00 ET review would print it (data through Fri 10-09)",
        f"fetch window passed to the shipped query: {seen['args'][0]} .. {seen['args'][1]}",
        "", "──── fold block ────", text, "", f"──── 'Also checked' phrase ────", phrase, "",
        "──── cross-check: shipped aggregate vs independent direct SELECT (same windows) ────",
        "window   | agg n  engine-themed  judge-themed | direct n  engine-themed  judge-themed | match",
    ]
    for c in checks:
        out.append(f"{c[0]:<8} | {c[1]:>5}  {c[2]:>13}  {c[3]:>12} | {c[4]:>8}  {c[5]:>13}  {c[6]:>12} | {'OK' if c[7] else 'MISMATCH'}")
    out += [
        "",
        f"adding source='live_scan' to the shadow side changes the 30d n from {counts['direct_trail']['n']} "
        f"to {ls['n']} (equal = the join to alerts alone already excludes the unscored rows)",
        f"context 30d: adjudicated alerts {counts['ctx_all_adjudicated_trail']['n']} · with any shadow row "
        f"{counts['ctx_adjudicated_with_shadow_row_trail']['n']} · with a CLEAN (bounded=unbounded) shadow row {tr['n']}",
        "",
        f"ALL MATCH: {all(c[7] for c in checks)}",
    ]
    (HERE / "sample_render.txt").write_text("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    {"gen": gen, "render": render}[sys.argv[1]]()
