#!/usr/bin/env python3
"""#694 tie-breaker test — dataset.csv -> results (printed; run as `python3 score.py > results.txt`).

LOCAL ONLY, NO NETWORK. Uses the real ep_rubric.shortlist_prescore / shortlist_sort_key so the
baselines are the production ranking, not a lookalike.

ORDERINGS per day (pool = the last pre-open tick's candidates, see build_dataset.py):
  A        today's live pre-open sort: composite with ADV EMPTY (65 in a theme / 32.5 not), ties A->Z
  B        fix (b) as signed: composite with last night's ADV$ (k1), tie-break continuous ADV$, then A->Z
  T:<key>  fix (b) composite, tie-break = <key> (missing ranks last), then A->Z
  S:<key>  <key> alone (missing ranks last), then A->Z
MEASURES:
  crowded days (pool > 20): names cut (rank > 20) per ordering, labelled names flagged
  within-day pairwise AUC: over same-day (labelled, unlabelled pool-mate) pairs, share where the
  labelled name ranks above (ties 0.5). "all rows": missing ranks last. "present": both have it.
"""
from __future__ import annotations

import csv
import sys
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[2]))
from agents.market_intelligence.ep_rubric import (  # noqa: E402
    SHORTLIST_SIZE, shortlist_prescore, shortlist_sort_key)

CUT = SHORTLIST_SIZE
KEYS = [  # (id, column, sign: +1 higher better / -1 lower better, plain name)
    ("adv$", "k1_adv_dollar", +1, "20-day avg dollar volume, last night (the signed key)"),
    ("pm$", "k2_pm_dollar", +1, "pre-market dollar volume so far"),
    ("pm_rvol", "k3_pm_rvol", +1, "pre-market volume vs normal at this minute"),
    ("rs_comp", "k4_rs_composite", +1, "last night's RS composite"),
    ("rs_rank", "k4_rs_rank", -1, "last night's RS rank (1 = strongest)"),
    ("zones", "k5_zones", +1, "resistance zones the gap clears (zones days only)"),
    ("gap", "k6_gap", +1, "gap % (CONTROL - known backwards)"),
    ("alpha", "k7_alpha", +1, "ticker A->Z (MEANINGLESS control: what 'no tie-breaker' does)"),
]


def fnum(x):
    return float(x) if x not in ("", None) else None


rows = list(csv.DictReader(open(HERE / "dataset.csv")))
pool = [r for r in rows if r["pool"] == "1"]
out_of_pool = [r for r in rows if r["pool"] == "0"]
for r in pool:
    for _, col, _, _ in KEYS:
        if col != "k7_alpha":
            r[col] = fnum(r[col])
    r["gap_pct"] = fnum(r["gap_pct"])
    r["in_theme"] = r["in_theme"] == "1"
    a = shortlist_prescore(adv_dollar=None, gap_pct=r["gap_pct"], in_active_theme=r["in_theme"])
    b = shortlist_prescore(adv_dollar=r["k1_adv_dollar"], gap_pct=r["gap_pct"],
                           in_active_theme=r["in_theme"])
    r["compA"], r["compB"] = a["composite"], b["composite"]

_alpha = {t: i for i, t in enumerate(sorted({r["ticker"] for r in pool}))}
for r in pool:
    r["k7_alpha"] = -float(_alpha[r["ticker"]])   # earlier in the alphabet = "higher"
days: dict[str, list[dict]] = defaultdict(list)
for r in pool:
    days[r["scan_date"]].append(r)
zones_days = set((HERE / "zones_days.txt").read_text().split())


def keyval(r, col, sign):
    v = r[col]
    return None if v is None else sign * v


def order(rs, name):
    if name == "A":
        k = lambda r: shortlist_sort_key(r["ticker"], r["compA"], None)
    elif name == "B":
        k = lambda r: shortlist_sort_key(r["ticker"], r["compB"], r["k1_adv_dollar"])
    else:
        kind, kid = name.split(":")
        _, col, sign, _ = next(x for x in KEYS if x[0] == kid)

        def k(r, col=col, sign=sign, kind=kind):
            v = keyval(r, col, sign)
            miss = (1, 0.0) if v is None else (0, -v)
            return ((-r["compB"],) if kind == "T" else ()) + miss + (r["ticker"],)
    return sorted(rs, key=k)


ORDERINGS = ["A", "B"] + [f"T:{k[0]}" for k in KEYS] + [f"S:{k[0]}" for k in KEYS]
rank: dict[str, dict[tuple[str, str], int]] = {o: {} for o in ORDERINGS}
for d, rs in days.items():
    for o in ORDERINGS:
        for i, r in enumerate(order(rs, o)):
            rank[o][(d, r["ticker"])] = i + 1

P = print
P("#694 TIE-BREAKER TEST — results (generated by score.py from dataset.csv; no network)")
P("=" * 100)

# ── sanity gates ───────────────────────────────────────────────────────────────────────
P("\n## SANITY GATES (stop if any fails)")
g_ok = g_n = 0
for d, rs in days.items():
    for r in rs:
        if r["rank_by_gap_logged"]:
            g_n += 1
            mine = 1 + sum(1 for x in rs if x["gap_pct"] > r["gap_pct"])
            g_ok += int(mine == int(r["rank_by_gap_logged"]))
P(f"1. logged rank_by_gap reproduced from gap_pct (desc): {g_ok} of {g_n} rows")
a_ok = a_n = 0
for d, rs in days.items():
    for r in rs:
        if r["rank_by_prescore_logged"]:
            a_n += 1
            a_ok += int(rank["A"][(d, r["ticker"])] == int(r["rank_by_prescore_logged"]))
P(f"2. logged rank_by_prescore (live since 2026-08-22) reproduced by ordering A "
  f"(ADV empty, ties A->Z): {a_ok} of {a_n} rows")
P("   (if 2 holds, the live pre-open order really is the collapsed alphabetical one)")

# ── population ─────────────────────────────────────────────────────────────────────────
P("\n## POPULATION")
P(f"pool rows {len(pool)} on {len(days)} days (2026-05-01..2026-10-08), one tick per day.")
ticks = defaultdict(int)
for d, rs in days.items():
    ticks[rs[0]["tick_et"]] += 1
P("last pre-open tick used: " + ", ".join(f"{t} on {n} days" for t, n in sorted(ticks.items())))
for d, rs in sorted(days.items()):
    if rs[0]["tick_et"] != "09:25:00":
        P(f"   {d}: scanner's last pre-open tick was {rs[0]['tick_et']} (no later pre-open tick ran)")
sizes = sorted(len(v) for v in days.values())
P(f"pool size per day: median {sizes[len(sizes)//2]}, max {sizes[-1]}; days > {CUT}: "
  f"{sum(1 for s in sizes if s > CUT)}")
lab = defaultdict(list)
for r in pool:
    if r["label"]:
        lab[r["label"]].append(f"{r['ticker']} {r['scan_date']}")
for L in ("REAL_EP", "GOOD_CHART", "OKISH_CHART", "BAD_CHART"):
    outs = [f"{r['ticker']} {r['scan_date']}" for r in out_of_pool if r["label"] == L]
    P(f"{L}: in pool {len(lab[L])} — {', '.join(lab[L])}")
    P(f"{' ' * len(L)}  OUT of pool {len(outs)} — {', '.join(outs)}")

P("\nkey coverage in the pool (rows with a value):")
for kid, col, _, nm in KEYS:
    have = sum(1 for r in pool if r[col] is not None)
    base = [r for r in pool if r["scan_date"] in zones_days] if kid == "zones" else pool
    have_b = sum(1 for r in base if r[col] is not None)
    P(f"  {kid:8} {have_b:5} of {len(base):5}  ({nm})")
k2src = defaultdict(int)
for r in pool:
    k2src[r["k2_src"]] += 1
P(f"  pre-market $ source: {dict(k2src)} (derived = rel_volume x adv x tick price, before 2026-08-29)")
miss_pm = defaultdict(lambda: [0, 0])
for r in pool:
    key = r["reject_stage"] or (r["filter_reason"][:28] if r["filter_reason"] else "<graded/none>")
    miss_pm[key][1] += 1
    miss_pm[key][0] += int(r["k3_pm_rvol"] is None)
P("  pm_rvol missing by row outcome (missing / rows) — it is written only when grading reached it:")
for k, (m, n) in sorted(miss_pm.items(), key=lambda x: -x[1][1])[:14]:
    P(f"     {m:4}/{n:4}  {k}")
P(f"  no RS/ADV row last night (not in mi_stock_scores' ~2,400-3,900 names): "
  f"{sum(1 for r in pool if r['k1_adv_dollar'] is None)} of {len(pool)} pool rows")
lab_noadv = [f"{r['ticker']} {r['scan_date']} ({r['label']})" for r in pool
             if r["label"] and r["k1_adv_dollar"] is None]
P(f"  labelled names with no ADV row: {', '.join(lab_noadv) or 'none'}")

# ── PRIMARY: crowded mornings ───────────────────────────────────────────────────────────
P("\n" + "=" * 100)
P(f"## PRIMARY — CROWDED MORNINGS (pool > {CUT} at the last pre-open tick)")
crowded = sorted(d for d, rs in days.items() if len(rs) > CUT)
surv = {o: {"REAL_EP": [0, 0], "GOOD/OKISH": [0, 0], "BAD_CHART": [0, 0]} for o in ORDERINGS}
for d in crowded:
    rs = days[d]
    ob = order(rs, "B")
    c20, c21 = ob[CUT - 1]["compB"], ob[CUT]["compB"]
    tie_grp = [r for r in rs if r["compB"] == c20]
    above = sum(1 for r in rs if r["compB"] > c20)
    no_adv = sum(1 for r in rs if r["k1_adv_dollar"] is None)
    P(f"\n### {d}  pool {len(rs)} at {rs[0]['tick_et']}  ({no_adv} names with no ADV row)")
    if c20 != c21:
        P(f"  fix (b): composite at rank {CUT} = {c20} vs rank {CUT+1} = {c21} -> the cut falls BETWEEN "
          f"score levels; NO tie-breaker can change who is cut this morning")
    else:
        P(f"  fix (b): rank {CUT} and {CUT+1} share composite {c20} -> {len(tie_grp)} names tied at the "
          f"cut, {above} above it, {CUT - above} slot(s) decided by the tie-breaker")
    P(f"  today's live order (A): all {len(rs)} tied at 65 or 32.5 — "
      f"{sum(1 for r in rs if r['in_theme'])} in a theme; the rest A->Z")
    labelled_today = [r for r in rs if r["label"]]
    if labelled_today:
        P("  labelled names today: " + ", ".join(f"{r['ticker']}={r['label']}" for r in labelled_today))
    for o in ORDERINGS:
        cut = [r for r in order(rs, o)[CUT:]]
        flag = [f"{r['ticker']}*{r['label']}" for r in cut if r["label"]]
        names = " ".join(r["ticker"] for r in cut)
        P(f"  {o:11} cut {len(cut):2}: {names}" + (f"   <<< CUTS {', '.join(flag)}" if flag else ""))
        for r in labelled_today:
            grp = "REAL_EP" if r["label"] == "REAL_EP" else (
                "BAD_CHART" if r["label"] == "BAD_CHART" else "GOOD/OKISH")
            surv[o][grp][1] += 1
            surv[o][grp][0] += int(rank[o][(d, r["ticker"])] <= CUT)

# ── SECONDARY: within-day pairwise AUC ──────────────────────────────────────────────────
P("\n" + "=" * 100)
P("## SECONDARY — WITHIN-DAY PAIRWISE SEPARATION (all pool days)")


def auc_key(group: set[str], col: str, sign: int, present_only: bool, lower_is_better=False):
    """share of (labelled, unlabelled same-day pool-mate) pairs where the labelled name's key is
    better; ties 0.5; missing = worst. Returns (auc, n_labelled, n_pairs, n_label_missing)."""
    num = n = 0.0
    used = set()
    miss = 0
    for d, rs in days.items():
        if col == "k5_zones" and d not in zones_days:
            continue
        labs = [r for r in rs if r["label"] in group]
        mates = [r for r in rs if not r["label"]]
        for L in labs:
            lv = keyval(L, col, sign)
            if lv is None:
                miss += 1
            for m in mates:
                mv = keyval(m, col, sign)
                if present_only and (lv is None or mv is None):
                    continue
                used.add((d, L["ticker"]))
                n += 1
                if lv is None and mv is None:
                    num += 0.5
                elif mv is None:
                    num += 1
                elif lv is None:
                    pass
                elif lv > mv:
                    num += 1
                elif lv == mv:
                    num += 0.5
    return (num / n if n else None), len(used), int(n), miss


def auc_order(group: set[str], o: str):
    num = n = 0
    used = set()
    for d, rs in days.items():
        labs = [r for r in rs if r["label"] in group]
        mates = [r for r in rs if not r["label"]]
        for L in labs:
            for m in mates:
                used.add((d, L["ticker"]))
                n += 1
                num += int(rank[o][(d, L["ticker"])] < rank[o][(d, m["ticker"])])
    return (num / n if n else None), len(used), n


GRP = {"REAL_EP": {"REAL_EP"}, "GOOD/OKISH": {"GOOD_CHART", "OKISH_CHART"}, "BAD_CHART": {"BAD_CHART"}}


def fmt(a):
    return "  n/a" if a is None else f"{a:.2f}"


P("\nPer KEY on its own (higher = labelled name ranks above its unlabelled pool-mates; 0.50 = coin flip;")
P("for BAD_CHART LOWER is better). 'all' = missing ranks last; 'present' = pairs where both have the key.")
P(f"{'key':9}| {'REAL EP all (n pos, pairs)':28}| {'REAL EP present (n, pairs)':27}| "
  f"{'GOOD/OKISH all':17}| {'BAD all':14}| {'pos missing':11}")
main_rows = {}
for kid, col, sign, nm in KEYS:
    ra = auc_key(GRP["REAL_EP"], col, sign, False)
    rp = auc_key(GRP["REAL_EP"], col, sign, True)
    ga = auc_key(GRP["GOOD/OKISH"], col, sign, False)
    gp = auc_key(GRP["GOOD/OKISH"], col, sign, True)
    ba = auc_key(GRP["BAD_CHART"], col, sign, False)
    bp = auc_key(GRP["BAD_CHART"], col, sign, True)
    main_rows[kid] = (ra, rp, ga, gp, ba, bp)
    P(f"{kid:9}| {fmt(ra[0])} ({ra[1]:2}, {ra[2]:4})            | {fmt(rp[0])} ({rp[1]:2}, {rp[2]:4})          "
      f"| {fmt(ga[0])} ({ga[1]:2},{ga[2]:4})| {fmt(ba[0])} ({ba[1]:2},{ba[2]:4})| {ra[3]}")
P("\nGOOD/OKISH and BAD_CHART, present-only:")
for kid, (ra, rp, ga, gp, ba, bp) in main_rows.items():
    P(f"  {kid:9} GOOD/OKISH {fmt(gp[0])} ({gp[1]}, {gp[2]} pairs)   BAD {fmt(bp[0])} ({bp[1]}, {bp[2]} pairs)")

P("\nPer full ORDERING (rank-based; what the shortlist would actually do):")
P(f"{'ordering':11}| {'REAL EP':18}| {'GOOD/OKISH':18}| {'BAD':18}| survive 20-cut on crowded days: "
  f"REAL EP / GOOD-OKISH / BAD")
for o in ORDERINGS:
    a1, a2, a3 = auc_order(GRP["REAL_EP"], o), auc_order(GRP["GOOD/OKISH"], o), auc_order(GRP["BAD_CHART"], o)
    s = surv[o]
    P(f"{o:11}| {fmt(a1[0])} ({a1[1]:2},{a1[2]:5}) | {fmt(a2[0])} ({a2[1]:2},{a2[2]:5}) | "
      f"{fmt(a3[0])} ({a3[1]:2},{a3[2]:5}) | {s['REAL_EP'][0]}/{s['REAL_EP'][1]}  "
      f"{s['GOOD/OKISH'][0]}/{s['GOOD/OKISH'][1]}  {s['BAD_CHART'][0]}/{s['BAD_CHART'][1]}")
P("  (survival is counted at each day's LAST pre-open check only; a name inside the top 20 at ANY earlier check that\n"
  "   morning is graded then, so earlier checks can only ADD survivors. Over the whole morning, ordering A keeps 3 of 5\n"
  "   real EPs — PLTR 08-04 and TEAM 08-07 were inside its top 20 at earlier checks; it cuts UMC and SNOW at every\n"
  "   check — see verify_population/v9_baselineA_every_tick.out. The pre-08-22 gap order cut SNOW only: ARM 05-06\n"
  "   was 18th by gap at 07:05 and was graded (score -12), per q04_label_rows.out.)")

# ── noise band: what a MEANINGLESS random key scores with these same positives ──────────
import random
rng = random.Random(694)
band, band_eq = [], []
_pos = [r for r in pool if r["label"] == "REAL_EP"]
for _ in range(2000):
    for r in pool:
        r["_rnd"] = rng.random()
    band.append(auc_key(GRP["REAL_EP"], "_rnd", +1, False)[0])
    _v = []
    for L in _pos:
        mates = [m for m in days[L["scan_date"]] if not m["label"]]
        _v.append(sum(1 for m in mates if L["_rnd"] > m["_rnd"]) / len(mates))
    band_eq.append(sum(_v) / len(_v))
band.sort()
band_eq.sort()
P(f"\nNOISE BAND — 2,000 random within-day orderings of the same pools: REAL-EP AUC 5th..95th "
  f"percentile = {band[100]:.2f}..{band[1899]:.2f} (median {band[1000]:.2f}). A key inside this band is "
  f"not distinguishable from a coin flip on this sample.")
P(f"  same band for the EQUAL-WEIGHT (each real EP once) reading: {band_eq[100]:.2f}..{band_eq[1899]:.2f}")

# ── how thin ───────────────────────────────────────────────────────────────────────────
P("\n## HOW THIN — per-positive share of its pool-mates it beats, per key (missing = worst)")
pos = sorted([r for r in pool if r["label"] == "REAL_EP"], key=lambda r: r["scan_date"])
hdr = f"{'positive':18}{'pool':>5}" + "".join(f"{k[0]:>9}" for k in KEYS)
P(hdr)
for L in pos:
    rs = days[L["scan_date"]]
    mates = [m for m in rs if not m["label"]]
    cells = []
    for kid, col, sign, _ in KEYS:
        if kid == "zones" and L["scan_date"] not in zones_days:
            cells.append("     n/a")
            continue
        lv = keyval(L, col, sign)
        s = 0.0
        for m in mates:
            mv = keyval(m, col, sign)
            s += (0.5 if lv is None and mv is None else 1 if mv is None else 0 if lv is None
                  else 1 if lv > mv else 0.5 if lv == mv else 0)
        cells.append(f"{s / len(mates):9.2f}" if mates else "      n/a")
    P(f"{L['ticker'] + ' ' + L['scan_date']:18}{len(rs):5}" + "".join(cells))
P("EQUAL-WEIGHT mean of the rows above (each real EP counts once; the pair-weighted AUC lets the three")
P("May names on 51-54-name mornings carry ~60% of all pairs):")
_eq = []
for kid, col, sign, _ in KEYS:
    vals = []
    for L in pos:
        if kid == "zones" and L["scan_date"] not in zones_days:
            continue
        mates = [m for m in days[L["scan_date"]] if not m["label"]]
        lv = keyval(L, col, sign)
        sc = 0.0
        for m in mates:
            mv = keyval(m, col, sign)
            sc += (0.5 if lv is None and mv is None else 1 if mv is None else 0 if lv is None
                   else 1 if lv > mv else 0.5 if lv == mv else 0)
        if mates:
            vals.append(sc / len(mates))
    _eq.append(f"{kid}={sum(vals)/len(vals):.2f} (n={len(vals)})")
P("  " + "  ".join(_eq))
_pairs_by_day = defaultdict(int)
for L in pos:
    _pairs_by_day[L["scan_date"]] += sum(1 for m in days[L["scan_date"]] if not m["label"])
_tot = sum(_pairs_by_day.values())
P(f"  share of the {_tot} real-EP pairs from 05-06 + 05-07: "
  f"{(_pairs_by_day['2026-05-06'] + _pairs_by_day['2026-05-07']) / _tot:.0%}")

# ── appendix: ranks ────────────────────────────────────────────────────────────────────
P("\n## APPENDIX — each labelled name's within-day rank / pool size under every ordering")
P("label       name/date          " + " ".join(f"{o:>9}" for o in ORDERINGS))
for r in sorted([r for r in pool if r["label"]], key=lambda r: (r["label"] != "REAL_EP", r["label"], r["scan_date"])):
    n = len(days[r["scan_date"]])
    P(f"{r['label'][:10]:11} {r['ticker'] + ' ' + r['scan_date']:18} "
      + " ".join(f"{str(rank[o][(r['scan_date'], r['ticker'])]) + '/' + str(n):>9}" for o in ORDERINGS))
P("\nlabelled names' raw key values:")
P(f"{'name/date':18} {'theme':>5} {'compB':>6} {'adv$M':>9} {'pm$K':>9} {'pm_rvol':>8} {'rs_comp':>8} "
  f"{'rs_rank':>8} {'zones':>6} {'gap':>6}  label")
for r in sorted([r for r in pool if r["label"]], key=lambda r: (r["label"] != "REAL_EP", r["label"], r["scan_date"])):
    def g(v, scale=1.0, nd=1):
        return "-" if v is None else f"{v / scale:.{nd}f}"
    P(f"{r['ticker'] + ' ' + r['scan_date']:18} {int(r['in_theme']):>5} {r['compB']:>6} "
      f"{g(r['k1_adv_dollar'], 1e6):>9} {g(r['k2_pm_dollar'], 1e3):>9} {g(r['k3_pm_rvol'], 1, 2):>8} "
      f"{g(r['k4_rs_composite']):>8} {g(r['k4_rs_rank'], 1, 0):>8} {g(r['k5_zones'], 1, 0):>6} "
      f"{g(r['k6_gap']):>6}  {r['label']}")
