-- READ-ONLY (SELECT only). Generated by run_probe.py gen. Run once; read q1_verify.out.
SELECT 'spend_rows' AS tag, s.caller, s.model, s.d::text, s.spend::text, s.calls::text, coalesce(s.in_tok,0)::text, coalesce(s.out_tok,0)::text FROM (
WITH et AS (
                SELECT cost_usd, caller, model, input_tokens, output_tokens,
                       (created_at AT TIME ZONE 'America/New_York')::date AS d
                FROM api_usage
                WHERE created_at >= '2026-10-11'::date - INTERVAL '32 days'
            )
            SELECT caller, model, d, SUM(cost_usd) AS spend, COUNT(*) AS calls,
                   SUM(input_tokens) AS in_tok, SUM(output_tokens) AS out_tok
            FROM et
            WHERE d BETWEEN '2026-10-11'::date - 29::int AND '2026-10-11'::date
            GROUP BY caller, model, d
) s;
SELECT 'pnl_rows' AS tag, p.account_mode, p.n::text, p.wins::text, p.total_pnl::text FROM (
SELECT account_mode,
                   COUNT(*)                               AS n,
                   COUNT(*) FILTER (WHERE total_pnl > 0)  AS wins,
                   COALESCE(SUM(total_pnl), 0)            AS total_pnl
              FROM mi_live_trades
             WHERE status = 'closed'
               AND total_pnl IS NOT NULL
               AND (closed_at AT TIME ZONE 'America/New_York')::date BETWEEN '2026-09-12'::date AND '2026-10-11'::date
             GROUP BY account_mode
) p;
SELECT 'direct_spend' AS tag, count(*)::text AS calls, round(sum(cost_usd)::numeric, 6)::text AS spend,
                   count(DISTINCT caller)::text AS callers
              FROM api_usage
             WHERE created_at >= ('2026-09-12'::timestamp AT TIME ZONE 'America/New_York')
               AND created_at <  (('2026-10-11'::date + 1)::timestamp AT TIME ZONE 'America/New_York');
SELECT 'direct_spend_top' AS tag, caller, round(sum(cost_usd)::numeric, 6)::text AS spend, count(*)::text AS calls
              FROM api_usage
             WHERE created_at >= ('2026-09-12'::timestamp AT TIME ZONE 'America/New_York')
               AND created_at <  (('2026-10-11'::date + 1)::timestamp AT TIME ZONE 'America/New_York')
             GROUP BY caller ORDER BY sum(cost_usd) DESC, caller LIMIT 6;
SELECT 'direct_pnl' AS tag, account_mode, count(*)::text AS n,
                   count(*) FILTER (WHERE total_pnl > 0)::text AS wins, round(sum(total_pnl)::numeric, 4)::text AS pnl
              FROM mi_live_trades
             WHERE status = 'closed' AND total_pnl IS NOT NULL
               AND closed_at >= ('2026-09-12'::timestamp AT TIME ZONE 'America/New_York')
               AND closed_at <  (('2026-10-11'::date + 1)::timestamp AT TIME ZONE 'America/New_York')
             GROUP BY account_mode ORDER BY account_mode;
SELECT 'ctx_closed_trades_list' AS tag, account_mode, ticker, (closed_at AT TIME ZONE 'America/New_York')::date::text AS closed_et,
                   round(total_pnl::numeric, 2)::text AS pnl
              FROM mi_live_trades
             WHERE status = 'closed' AND closed_at >= ('2026-09-12'::timestamp AT TIME ZONE 'America/New_York')
             ORDER BY closed_at;
