"""#313 part 2 weekly block - prod verification driver (READ-ONLY; SELECT only on prod).

  python scripts/probes/_wk1010_313/run_probe.py gen      # writes q1_verify.sql
  ssh apollo@87.99.134.162 "docker exec -i apollo-postgres psql -U apollo -d apollo -A -F $'\\t'" \\
      < scripts/probes/_wk1010_313/q1_verify.sql > scripts/probes/_wk1010_313/q1_verify.out
  python scripts/probes/_wk1010_313/run_probe.py render   # parses the .out, runs the REAL
                                                          # compute_caller_spend_window + section,
                                                          # writes sample_render.txt + the cross-check

Both shipped queries are CAPTURED through a recording pool (what runs on prod is byte-for-byte what
ships); the cross-check SQL is written independently (timestamp-range windows and a flat SUM instead
of the shipped ET-date-cast / per-(caller, model, day) group), so a window or summing bug cannot
hide behind a copy of itself.
"""
import asyncio
import sys
from datetime import date, timedelta
from pathlib import Path
from unittest.mock import AsyncMock, patch

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
sys.path.insert(0, str(ROOT))

TODAY = date(2026, 10, 11)                       # the Sunday run; data complete through Fri 10-09
START = TODAY - timedelta(days=29)               # the 30-ET-day window, inclusive


def _recording_pool():
    from tests.conftest import make_mock_pool
    pool, conn = make_mock_pool()
    conn.fetch = AsyncMock(return_value=[])
    return pool, conn


def _inline(sql: str, args: tuple) -> str:
    out = sql
    for i, a in reversed(list(enumerate(args, 1))):
        lit = f"'{a}'" if isinstance(a, date) else str(a)
        out = out.replace(f"${i}::date", f"{lit}::date").replace(f"${i}::int", f"{lit}::int").replace(f"${i}", lit)
    return out.strip().rstrip(";")


def _capture_spend_sql() -> str:
    import agents.market_intelligence.cost_board as cb
    pool, conn = _recording_pool()

    async def go():
        with patch.object(cb, "get_pool", new=AsyncMock(return_value=pool)):
            await cb.compute_caller_spend_window(TODAY, 30)
    asyncio.run(go())
    return _inline(conn.fetch.await_args.args[0], conn.fetch.await_args.args[1:])


def _capture_pnl_sql() -> str:
    import agents.market_intelligence.db as dbmod
    pool, conn = _recording_pool()

    async def go():
        with patch.object(dbmod, "get_pool", new=AsyncMock(return_value=pool)):
            await dbmod.get_closed_pnl_by_account_mode(START, TODAY)
    asyncio.run(go())
    assert conn.fetch.await_args.args[1:] == (START, TODAY)
    return _inline(conn.fetch.await_args.args[0], conn.fetch.await_args.args[1:])


def gen() -> None:
    d1, d2 = START, TODAY
    parts = [
        "-- READ-ONLY (SELECT only). Generated by run_probe.py gen. Run once; read q1_verify.out.",
        # shipped spend read: grouped (caller, model, day) rows, exactly what _fetch_caller_window returns
        "SELECT 'spend_rows' AS tag, s.caller, s.model, s.d::text, s.spend::text, s.calls::text, "
        "coalesce(s.in_tok,0)::text, coalesce(s.out_tok,0)::text FROM (",
        _capture_spend_sql(), ") s;",
        # shipped P&L read
        "SELECT 'pnl_rows' AS tag, p.account_mode, p.n::text, p.wins::text, p.total_pnl::text FROM (",
        _capture_pnl_sql(), ") p;",
        # INDEPENDENT cross-checks, same dates, different formulation
        f"""SELECT 'direct_spend' AS tag, count(*)::text AS calls, round(sum(cost_usd)::numeric, 6)::text AS spend,
                   count(DISTINCT caller)::text AS callers
              FROM api_usage
             WHERE created_at >= ('{d1}'::timestamp AT TIME ZONE 'America/New_York')
               AND created_at <  (('{d2}'::date + 1)::timestamp AT TIME ZONE 'America/New_York');""",
        f"""SELECT 'direct_spend_top' AS tag, caller, round(sum(cost_usd)::numeric, 6)::text AS spend, count(*)::text AS calls
              FROM api_usage
             WHERE created_at >= ('{d1}'::timestamp AT TIME ZONE 'America/New_York')
               AND created_at <  (('{d2}'::date + 1)::timestamp AT TIME ZONE 'America/New_York')
             GROUP BY caller ORDER BY sum(cost_usd) DESC, caller LIMIT 6;""",
        f"""SELECT 'direct_pnl' AS tag, account_mode, count(*)::text AS n,
                   count(*) FILTER (WHERE total_pnl > 0)::text AS wins, round(sum(total_pnl)::numeric, 4)::text AS pnl
              FROM mi_live_trades
             WHERE status = 'closed' AND total_pnl IS NOT NULL
               AND closed_at >= ('{d1}'::timestamp AT TIME ZONE 'America/New_York')
               AND closed_at <  (('{d2}'::date + 1)::timestamp AT TIME ZONE 'America/New_York')
             GROUP BY account_mode ORDER BY account_mode;""",
        f"""SELECT 'ctx_closed_trades_list' AS tag, account_mode, ticker, (closed_at AT TIME ZONE 'America/New_York')::date::text AS closed_et,
                   round(total_pnl::numeric, 2)::text AS pnl
              FROM mi_live_trades
             WHERE status = 'closed' AND closed_at >= ('{d1}'::timestamp AT TIME ZONE 'America/New_York')
             ORDER BY closed_at;""",
    ]
    (HERE / "q1_verify.sql").write_text("\n".join(parts) + "\n")
    print("wrote", HERE / "q1_verify.sql")


def _parse():
    spend_rows, pnl_rows, direct, top, pnl_direct, ctx = [], [], {}, [], [], []
    for ln in (HERE / "q1_verify.out").read_text().splitlines():
        c = ln.split("\t")
        if not c or not c[0]:
            continue
        if c[0].startswith("ERROR"):
            raise SystemExit(f"prod error in q1_verify.out: {ln}")
        t = c[0]
        if t == "spend_rows":
            spend_rows.append({"caller": c[1], "model": c[2], "d": date.fromisoformat(c[3]),
                               "spend": float(c[4]), "calls": int(c[5]), "in_tok": int(c[6]), "out_tok": int(c[7])})
        elif t == "pnl_rows":
            pnl_rows.append({"account_mode": c[1], "n": int(c[2]), "wins": int(c[3]), "total_pnl": float(c[4])})
        elif t == "direct_spend" and c[1] != "calls":
            direct = {"calls": int(c[1]), "spend": float(c[2]), "callers": int(c[3])}
        elif t == "direct_spend_top" and c[1] != "caller":
            top.append({"caller": c[1], "spend": float(c[2]), "calls": int(c[3])})
        elif t == "direct_pnl" and c[1] != "account_mode":
            pnl_direct.append({"account_mode": c[1], "n": int(c[2]), "wins": int(c[3]), "pnl": float(c[4])})
        elif t == "ctx_closed_trades_list" and c[1] != "account_mode":
            ctx.append(c[1:])
    return spend_rows, pnl_rows, direct, top, pnl_direct, ctx


def render() -> None:
    import agents.market_intelligence.cost_board as cb
    import agents.market_intelligence.system_review as sr
    spend_rows, pnl_rows, direct, top, pnl_direct, ctx = _parse()
    seen = {}

    async def fake_window_fetch(today, lookback):
        seen["spend_args"] = (today, lookback)
        return spend_rows

    async def fake_pnl(a, b):
        seen["pnl_args"] = (a, b)
        return pnl_rows
    cb._fetch_caller_window = fake_window_fetch              # the ONLY things replaced: the two DB drivers
    sr.get_closed_pnl_by_account_mode = fake_pnl
    text, phrase = asyncio.run(sr._spend_vs_pnl_section(TODAY))

    shipped = asyncio.run(cb.compute_caller_spend_window(TODAY, 30))
    s_total = round(sum(c["spend"] for c in shipped), 6)
    s_calls = sum(c["calls"] for c in shipped)
    checks = [("total spend", f"{s_total:.6f}", f"{direct['spend']:.6f}", abs(s_total - direct["spend"]) < 1e-4),
              ("total calls", s_calls, direct["calls"], s_calls == direct["calls"]),
              ("callers", len(shipped), direct["callers"], len(shipped) == direct["callers"])]
    for i, t in enumerate(top):
        got = shipped[i]
        checks.append((f"top{i + 1} {t['caller']}", f"{got['caller']} {got['spend']:.4f}/{got['calls']}",
                       f"{t['caller']} {t['spend']:.4f}/{t['calls']}",
                       got["caller"] == t["caller"] and abs(got["spend"] - t["spend"]) < 1e-4 and got["calls"] == t["calls"]))
    by_s = {r["account_mode"]: r for r in pnl_rows}
    by_d = {r["account_mode"]: r for r in pnl_direct}
    for mode in sorted(set(by_s) | set(by_d)):
        s, d = by_s.get(mode), by_d.get(mode)
        ok = bool(s and d and s["n"] == d["n"] and s["wins"] == d["wins"] and abs(s["total_pnl"] - d["pnl"]) < 5e-3)
        checks.append((f"P&L {mode}", f"n={s and s['n']} wins={s and s['wins']} pnl={s and round(s['total_pnl'], 2)}",
                       f"n={d and d['n']} wins={d and d['wins']} pnl={d and round(d['pnl'], 2)}", ok))
    out = [
        "#313 part 2 sample render - as the Sun 2026-10-11 08:00 ET review would print it (data through Fri 10-09)",
        f"spend fetch args (today, lookback): {seen['spend_args']} · P&L window: {seen['pnl_args'][0]} .. {seen['pnl_args'][1]}",
        "", "---- fold block ----", text, "", "---- 'Also checked' phrase ----", phrase, "",
        "---- cross-check: shipped read vs independent direct SELECT (same 30 ET days, different formulation) ----",
    ]
    for name, a, b, ok in checks:
        out.append(f"{'OK      ' if ok else 'MISMATCH'} {name:<34} shipped={a}  direct={b}")
    out += ["", "---- the closed trades in the window (context for the P&L line) ----"]
    out += ["  " + " ".join(r) for r in ctx]
    out += ["", f"ALL MATCH: {all(c[3] for c in checks)}"]
    (HERE / "sample_render.txt").write_text("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    {"gen": gen, "render": render}[sys.argv[1]]()
