"""Real-request samples for the pre-adoption replay (#690, 2026-09-30).

WHY. On 2026-09-28 the nightly refresh adopted claude-sonnet-5-5 after it passed the four-prompt
synthetic canary (shared/llm_client.run_canary) — and the model then refused our REAL theme
prompts. Nobody knew until the night run failed. A synthetic prompt proves the request SHAPE
works; only our own requests prove the model will answer them. So every production call keeps a
few of its real requests on disk, and the refresh replays them on a new release before adopting
it (agents/market_intelligence/model_resolution.py).

WHAT IS STORED. One JSON file per CALL SITE under `logs/llm_samples/` (env
`APOLLO_LLM_SAMPLE_DIR`), holding the LAST 3 samples. A sample is:
  * the request exactly as the CALLER wrote it (before shared/llm_client adapts it — a replay
    re-adapts for the candidate model), model included;
  * the answer callers parse: stop_reason, then the tool name + tool input for a tool answer,
    else the first 500 characters of text;
  * `replayable` — False when the request carried an image (stored as a marker, never the bytes)
    or a model-signed thinking block from an earlier turn (replaying one model's signature on
    another is a 400 that would read as a false failure).

THE KEY is the call site — `module:function` of the first frame outside shared/llm_client and
outside the pass-through wrappers below, which collapse several callers (and roles) at one frame.
`shared/llm_call_sites.py` (generated by scripts/gen_llm_call_sites.py from an AST scan, gated by
tests/test_llm_call_sites.py) maps each key to the ROLE its model argument names.

WHAT IS NOT STORED.
  * operator chat (ORCHESTRATOR; the market agent's general handler, which carries the operator's
    typed questions), conversation compression, the health ping (EXCLUDED_ROLES);
  * any request carrying a REAL-LOOKING credential — a `key=`/`token=`/`Bearer`/`Basic` match of
    `shared.secret_redaction`'s patterns whose VALUE is >= 16 characters with a digit AND a letter
    (`credential_like`). Dropped whole, and COUNTED in the key's file (`skipped.credential_like`)
    so a starved call site is visible in the digest. This is deliberately NARROWER than
    `redact_secrets` (which guards the audit log and stays conservative): that one also masks
    "Sector: Basic Materials" and "sort key=value", which starved the theme and judge prompts;
  * refusals and truncations (not answers);
  * anything while capture is disabled (the canary and the replay itself — `capture_disabled()`).

CONTRACT. `record()` never raises into an LLM call; a key makes at most ONE capture attempt
(read, serialize, redact, write) per 60 minutes WHATEVER the outcome — stored, credential-like,
unserializable or unwritable all spend the hour, so a call site that can never be stored does not
repeat the work on every call; an unwritable directory (the orchestrator mounts logs read-only) is
skipped with a debug line. Plain synchronous file IO — the sync client has no loop, and it happens
at most once an hour per key.
"""
from __future__ import annotations

import contextlib
import json
import logging
import os
import re
import tempfile
import time
from contextvars import ContextVar
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterator, Optional

# The private patterns are imported rather than copied so the two can never drift apart; only the
# decision about WHEN a match is a credential differs (see credential_like).
from shared.secret_redaction import _BEARER, _QS_SECRET

logger = logging.getLogger(__name__)

__all__ = [
    "PASSTHROUGH_MODULES",
    "PASSTHROUGH_FUNCTIONS",
    "EXCLUDED_ROLES",
    "UNTRACKED",
    "credential_like",
    "call_site_key",
    "capture_disabled",
    "capture_is_disabled",
    "record",
    "answer_summary",
    "sample_dir",
    "load_all",
]

SCHEMA = 1
KEEP = 3
THROTTLE_SECONDS = 60 * 60
TEXT_CAP = 500
UNTRACKED = "UNTRACKED"
_DIR_ENV = "APOLLO_LLM_SAMPLE_DIR"

# ── Pass-through frames (ONE list — the stack walk and the AST generator both read it) ──────
# A frame here is not a call site: it is shared plumbing several callers go through, often with
# DIFFERENT models (judge_transport serves the grade judge, the management judge and the
# second-opinion check). The key is the first frame past them.
PASSTHROUGH_MODULES: frozenset[str] = frozenset({
    "agents.market_intelligence.judge_transport",
})
PASSTHROUGH_FUNCTIONS: frozenset[tuple[str, str]] = frozenset({
    ("agents.market_intelligence.theme_engine", "_assignment_turn"),
    ("agents.market_intelligence.theme_merge_arm", "_create_with_backoff"),
    # Not in the #690 brief's list, added on the same criterion: grade_holistic takes `model`
    # from its caller, so the live grade (JUDGE_MODEL) and judge_divergence's second opinion
    # (JUDGE_DIVERGENCE_MODEL — a different tier) would otherwise share one key and one role.
    ("agents.market_intelligence.ep_grade_judge", "grade_holistic"),
})
# Infrastructure frames between a caller and the transport (asyncio.wait_for, contextlib).
_INFRA_PREFIXES = ("asyncio", "contextlib", "functools", "concurrent.")
_SELF_MODULES = frozenset({"shared.llm_client", __name__})

# Operator chat / compressed chat / a 5-token ping — never written to disk. MARKET_AGENT_MODEL's
# only call site (agent.py `_handle_general`) answers the operator's own typed questions: the same
# privacy class as ORCHESTRATOR/COMPRESSION, so the same rule.
EXCLUDED_ROLES: frozenset[str] = frozenset({
    "ORCHESTRATOR_MODEL", "COMPRESSION_MODEL", "HEALTHCHECK_MODEL", "MARKET_AGENT_MODEL",
})

_CAPTURE_OFF: ContextVar[bool] = ContextVar("apollo_llm_capture_off", default=False)
# key -> wall time of the last capture ATTEMPT, this process (the file is the cross-restart
# truth). Set before any IO-heavy work, so every outcome — stored, credential-like, unserializable,
# unwritable — counts as the hour's one attempt.
_last_attempt: dict[str, float] = {}

# A `key=` / `Bearer` match is a real credential only when its VALUE looks like one: long enough,
# and mixing letters with digits. Below this, "Basic Materials" / "sort key=value" are prose.
_CRED_MIN_LEN = 16


@contextlib.contextmanager
def capture_disabled() -> Iterator[None]:
    """No sample is recorded inside this block — nor in tasks created inside it (they copy the
    context). Used by the canary and the replay, so synthetic calls never become samples."""
    token = _CAPTURE_OFF.set(True)
    try:
        yield
    finally:
        _CAPTURE_OFF.reset(token)


def capture_is_disabled() -> bool:
    return _CAPTURE_OFF.get()


def sample_dir() -> Path:
    env = os.environ.get(_DIR_ENV)
    if env:
        return Path(env)
    return Path(__file__).resolve().parents[1] / "logs" / "llm_samples"


def _is_passthrough(module: str, function: str) -> bool:
    if module in _SELF_MODULES or module in PASSTHROUGH_MODULES:
        return True
    if (module, function) in PASSTHROUGH_FUNCTIONS:
        return True
    return module.startswith(_INFRA_PREFIXES)


def call_site_key(frame) -> Optional[str]:
    """`module:function` of the first frame (walking outward from `frame`) that is not the
    transport, not a pass-through wrapper and not asyncio plumbing. None if there is none."""
    f = frame
    depth = 0
    while f is not None and depth < 64:
        module = str(f.f_globals.get("__name__") or "")
        function = f.f_code.co_name
        if module and not _is_passthrough(module, function):
            return f"{module}:{function}"
        f = f.f_back
        depth += 1
    return None


def _role_for(key: str) -> Optional[str]:
    from shared.llm_call_sites import CALL_SITES
    return CALL_SITES.get(key)


# ── Serialization ─────────────────────────────────────────────────────────────

class _NotSerializable(TypeError):
    pass


def _jsonable(obj: Any, depth: int = 0) -> Any:
    """Plain JSON data from a request/answer. SDK blocks go through `model_dump`; anything else
    that is not plain data raises (the sample is skipped — a half-serialized request would
    replay as something the caller never sent)."""
    if depth > 40:
        raise _NotSerializable("nesting too deep")
    if obj is None or isinstance(obj, (bool, int, float, str)):
        return obj
    if isinstance(obj, dict):
        return {str(k): _jsonable(v, depth + 1) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_jsonable(v, depth + 1) for v in obj]
    dump = getattr(obj, "model_dump", None)
    if callable(dump):
        try:
            dumped = dump(mode="json", exclude_none=True)
        except TypeError:
            dumped = dump()
        if isinstance(dumped, dict):
            return _jsonable(dumped, depth + 1)
    raise _NotSerializable(f"cannot serialize {type(obj).__name__}")


def _scrub_images(node: Any) -> tuple[Any, bool]:
    """(copy with every image block replaced by a marker, whether any was found)."""
    if isinstance(node, dict):
        if node.get("type") == "image":
            src = node.get("source") if isinstance(node.get("source"), dict) else {}
            data = src.get("data") if isinstance(src.get("data"), str) else ""
            return {"type": "image", "omitted": True,
                    "media_type": src.get("media_type"), "chars": len(data)}, True
        found = False
        out = {}
        for k, v in node.items():
            out[k], f = _scrub_images(v)
            found = found or f
        return out, found
    if isinstance(node, list):
        found = False
        out_list = []
        for v in node:
            nv, f = _scrub_images(v)
            out_list.append(nv)
            found = found or f
        return out_list, found
    return node, False


def _carries_signed_thinking(request: dict) -> bool:
    for msg in request.get("messages") or []:
        if not isinstance(msg, dict) or msg.get("role") != "assistant":
            continue
        content = msg.get("content")
        if isinstance(content, list) and any(
                isinstance(b, dict) and b.get("type") in ("thinking", "redacted_thinking")
                for b in content):
            return True
    return False


def _block_type(b: Any) -> str:
    return str(b.get("type") if isinstance(b, dict) else getattr(b, "type", "") or "")


def answer_summary(resp: Any) -> dict:
    """The part of an answer callers parse: stop_reason, then the FIRST tool call (name + input)
    or, with no tool call, the first 500 characters of text."""
    from shared.llm_response import first_text, stop_reason
    out: dict = {"stop_reason": stop_reason(resp)}
    for b in (resp.get("content") if isinstance(resp, dict) else getattr(resp, "content", None)) or []:
        if _block_type(b) == "tool_use":
            name = b.get("name") if isinstance(b, dict) else getattr(b, "name", None)
            inp = b.get("input") if isinstance(b, dict) else getattr(b, "input", None)
            out["tool"] = str(name) if name is not None else None
            out["tool_input"] = _jsonable(inp) if isinstance(inp, dict) else {}
            return out
    out["text"] = first_text(resp)[:TEXT_CAP]
    return out


_TICKER_RE = re.compile(r"\bTicker:\s*\$?([A-Z][A-Z0-9.]{0,9})\b")


def _subject(request: dict) -> str:
    """A ticker the prompt names ("Ticker: ABCD"), for the operator digest; "" if none."""
    for msg in request.get("messages") or []:
        content = msg.get("content") if isinstance(msg, dict) else None
        texts = [content] if isinstance(content, str) else [
            b.get("text") for b in content or [] if isinstance(b, dict) and isinstance(b.get("text"), str)]
        for t in texts:
            m = _TICKER_RE.search(t or "")
            if m:
                return m.group(1)
    return ""


# ── Files ─────────────────────────────────────────────────────────────────────

def _file_for(key: str, directory: Path) -> Path:
    return directory / (re.sub(r"[^A-Za-z0-9_.-]", "_", key.replace(":", "__")) + ".json")


def _read(path: Path) -> Optional[dict]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    return data if isinstance(data, dict) and isinstance(data.get("samples"), list) else None


def _write_atomic(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=path.name, suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(payload, f, sort_keys=True, ensure_ascii=False)
        os.replace(tmp, path)
    except BaseException:
        with contextlib.suppress(OSError):
            os.unlink(tmp)
        raise


def _latest_ts(data: Optional[dict]) -> Optional[float]:
    best = None
    for s in (data or {}).get("samples") or []:
        try:
            ts = datetime.fromisoformat(str(s.get("captured_at"))).timestamp()
        except (TypeError, ValueError):
            continue
        best = ts if best is None or ts > best else best
    return best


def _empty(key: str, role: str) -> dict:
    return {"schema": SCHEMA, "key": key, "role": role, "samples": [], "skipped": {}}


def _strings(node: Any) -> Iterator[str]:
    """Every string in a JSON-able request: dict keys and leaf values."""
    if isinstance(node, str):
        yield node
    elif isinstance(node, dict):
        for k, v in node.items():
            yield str(k)
            yield from _strings(v)
    elif isinstance(node, list):
        for v in node:
            yield from _strings(v)


def _value_looks_like_credential(value: str) -> bool:
    return (len(value) >= _CRED_MIN_LEN and any(c.isdigit() for c in value)
            and any(c.isalpha() for c in value))


def credential_like(request: Any) -> bool:
    """True when the request carries a REAL-LOOKING credential: a match of secret_redaction's
    `key=`-style or `Bearer`/`Basic` pattern whose value is >= 16 characters with at least one
    digit AND one letter. Stricter than `redact_secrets` on purpose — that one guards the audit log
    and masks "Sector: Basic Materials" and "sort key=value", which would starve the theme and
    judge call sites of samples."""
    for text in _strings(request):
        for pattern in (_QS_SECRET, _BEARER):
            for m in pattern.finditer(text):
                if _value_looks_like_credential(m.group(2)):
                    return True
    return False


def _note_credential_skip(key: str, role: str, path: Path, now: float) -> None:
    """Count one credential-like drop in the key's file. Called at most once an hour per key (the
    attempt throttle in `_record`), so the count is hourly attempts dropped, not raw calls."""
    data = _read(path) or _empty(key, role)
    skipped = data.setdefault("skipped", {})
    entry = skipped.get("credential_like") if isinstance(skipped.get("credential_like"), dict) else {}
    skipped["credential_like"] = {"count": int(entry.get("count") or 0) + 1,
                                  "last_at": datetime.fromtimestamp(now, timezone.utc).isoformat()}
    _write_atomic(path, data)


def record(kw: dict, resp: Any, *, frame) -> str:
    """Record one production request + answer. Returns what happened (tests read it; the
    transport ignores it). NEVER raises."""
    try:
        return _record(kw, resp, frame)
    except OSError as e:
        logger.debug("llm_samples: sample directory not writable, skipped: %s", e)
        return "unwritable"
    except Exception as e:  # loud-ok: capture is best-effort and must never touch the LLM call
        logger.debug("llm_samples: capture failed, skipped: %s: %s", type(e).__name__, e)
        return "error"


def _record(kw: dict, resp: Any, frame) -> str:
    if _CAPTURE_OFF.get():
        return "disabled"
    key = call_site_key(frame)
    if not key:
        return "no_key"
    role = _role_for(key)
    if not role or role == UNTRACKED:
        return "untracked"
    if role in EXCLUDED_ROLES:
        return "excluded"
    from shared.llm_response import stop_reason
    if stop_reason(resp) in ("max_tokens", "refusal"):
        return "not_an_answer"

    now = time.time()
    last = _last_attempt.get(key)
    if last is not None and now - last < THROTTLE_SECONDS:
        return "throttled"
    directory = sample_dir()
    path = _file_for(key, directory)
    existing: Optional[dict] = None
    if last is None:            # first call for this key in this process: the file is the truth
        existing = _read(path)
        on_disk = _latest_ts(existing)
        if on_disk is not None and now - on_disk < THROTTLE_SECONDS:
            _last_attempt[key] = on_disk
            return "throttled"
    # From here the key has spent its hour: whatever happens next (unserializable, credential-like,
    # an unwritable directory, a stored sample) is not retried until THROTTLE_SECONDS have passed.
    _last_attempt[key] = now

    try:
        request = _jsonable(dict(kw))
    except _NotSerializable as e:
        logger.debug("llm_samples: %s request not serializable (%s), skipped", key, e)
        return "unserializable"
    request, had_image = _scrub_images(request)
    if credential_like(request):
        _note_credential_skip(key, role, path, now)
        return "credential_like"

    unreplayable = "image" if had_image else ("signed thinking in history"
                                               if _carries_signed_thinking(request) else "")
    sample = {
        "captured_at": datetime.fromtimestamp(now, timezone.utc).isoformat(),
        "model": request.get("model"),
        "role": role,
        "replayable": not unreplayable,
        "request": request,
        "answer": answer_summary(resp),
        "subject": _subject(request),
    }
    if unreplayable:
        sample["unreplayable_reason"] = unreplayable
    data = (existing if existing is not None else _read(path)) or _empty(key, role)
    data["role"] = role
    data["samples"] = (list(data.get("samples") or []) + [sample])[-KEEP:]
    _write_atomic(path, data)
    return "stored"


def load_all(directory: Optional[Path] = None) -> list[dict]:
    """Every readable sample file (one per call-site key). Unreadable files are skipped."""
    d = directory or sample_dir()
    try:
        paths = sorted(d.glob("*.json"))
    except OSError:
        return []
    out = []
    for p in paths:
        data = _read(p)
        if data and isinstance(data.get("key"), str):
            out.append(data)
    return out


def reset_throttle() -> None:
    """Tests only: forget the in-process throttle state."""
    _last_attempt.clear()
