"""GENERATED by scripts/gen_llm_call_sites.py — do not edit by hand (#690).

Call-site key (`module:function`, the first frame outside shared/llm_client and the pass-through
wrappers — shared/llm_samples.call_site_key) -> the model ROLE that call's `model=` argument names,
or "UNTRACKED" for a raw tier pin / literal id that follows no role. The pre-adoption replay
(agents/market_intelligence/model_resolution.py) uses it to decide which captured requests a tier
move must replay. Regenerate after adding or moving a messages.create:

    python3 scripts/gen_llm_call_sites.py

tests/test_llm_call_sites.py fails when this file is stale.
"""

CALL_SITES: dict[str, str] = {
    'agents.market_intelligence.agent:_handle_general': 'MARKET_AGENT_MODEL',
    'agents.market_intelligence.catalyst_materiality:judge_materiality_llm': 'MATERIALITY_MODEL',
    'agents.market_intelligence.catalyst_type_classifier:classify_catalyst_type': 'CATALYST_TYPE_MODEL',
    'agents.market_intelligence.chart_axis:grade_one': 'JUDGE_MODEL',
    'agents.market_intelligence.ecosystem_discovery:propose_ecosystem_via_llm': 'SYNTHESIS_MODEL',
    'agents.market_intelligence.ep_detector:_classify_catalyst_claude': 'GROUNDED_GRADE_MODEL',
    'agents.market_intelligence.ep_detector:_judge_shadow': 'JUDGE_MODEL',
    'agents.market_intelligence.judge_divergence:_run': 'JUDGE_DIVERGENCE_MODEL',
    'agents.market_intelligence.judge_named_themes:extract_named_themes': 'JUDGE_NAMED_THEMES_MODEL',
    'agents.market_intelligence.mgmt_judge:manage_holistic': 'JUDGE_MODEL',
    'agents.market_intelligence.postmortem:generate_postmortem_narrative': 'POSTMORTEM_MODEL',
    'agents.market_intelligence.scheduler:_nightly_data_pull': 'DESCRIPTION_MODEL',
    'agents.market_intelligence.system_review:_synthesize': 'SYSTEM_REVIEW_MODEL',
    'agents.market_intelligence.theme_ecosystems:_assign_via_haiku': 'ECOSYSTEM_ASSIGN_MODEL',
    'agents.market_intelligence.theme_engine:_call_advisor': 'THEME_ADVISOR_MODEL',
    'agents.market_intelligence.theme_engine:_discover_lane2_registry': 'THEME_MODEL',
    'agents.market_intelligence.theme_engine:_discover_new_themes_single': 'THEME_MODEL',
    'agents.market_intelligence.theme_engine:_ensure_descriptions': 'DESCRIPTION_MODEL',
    'agents.market_intelligence.theme_engine:_propose_assignment_batch': 'THEME_MODEL',
    'agents.market_intelligence.theme_engine:_rename_theme_to_fit_cluster': 'THEME_MODEL',
    'agents.market_intelligence.theme_engine:_split_fat_theme': 'THEME_MODEL',
    'agents.market_intelligence.theme_engine:_validate_theme_membership': 'THEME_MODEL',
    'agents.market_intelligence.theme_engine:discover_narrative_themes': 'THEME_MODEL',
    'agents.market_intelligence.theme_engine:judge_theme_fit': 'THEME_MODEL',
    'agents.market_intelligence.theme_merge_arm:adjudicate_containment_pair': 'THEME_PARENT_ADJUDICATION_MODEL',
    'agents.market_intelligence.theme_merge_arm:adjudicate_merge_pair': 'UNTRACKED',
    'agents.market_intelligence.theme_synthesis:run_theme_synthesis': 'SYNTHESIS_MODEL',
    'channels.telegram:_check_claude': 'HEALTHCHECK_MODEL',
    'core.context:_summarize_messages': 'COMPRESSION_MODEL',
    'core.orchestrator:_tool_use_loop': 'ORCHESTRATOR_MODEL',
}
